### ISSUE TITLE
eslint-plugin-mocha@5.0.0 does not support node 4

### ISSUE THREAD

**Issue by shianqi** [lo1tuma/eslint-plugin-mocha#160]
```
npm run eslint

> mi-insight-web@2.0.0 eslint /Users/archie/seniverse/mi-insight-web
> eslint --ext .js,jsx ./src

Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/archie/seniverse/mi-insight-web/node_modules/eslint-plugin-mocha/index.js:5:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 17.5.0
npm ERR! argv "/Users/archie/.nvm/versions/node/v4.8.5/bin/node" "/Users/archie/.nvm/versions/node/v4.8.5/bin/npm" "run" "eslint"
npm ERR! node v4.8.5
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! mi-insight-web@2.0.0 eslint: `eslint --ext .js,jsx ./src `
npm ERR! Exit status 1
```

**Comment by lo1tuma** [comment]
Hi @shianqi. You are right, we dropped support for nodejs 4 intentionally with the 5.0.0 release of eslint-plugin-mocha, this is even mentioned in the [release notes](https://github.com/lo1tuma/eslint-plugin-mocha/releases/tag/5.0.0) as breaking change.
As nodejs 4 will reach its end of life at the end of this month I don’t think it is worth to put any effort into supporting such an old nodejs version. So I would recommend to upgrade to a newer version of nodejs or to continue using eslint-plugin-mocha 4.x.
