### ISSUE TITLE
v10.0.4 crashes on node 17

### ISSUE THREAD

**Issue by mantoni** [lo1tuma/eslint-plugin-mocha#324]
Hi there,

Upgrading from `v10.0.3` to `v10.0.4` causes the following error on node `v17.3.1`:

```
> eslint .


Oops! Something went wrong! :(

ESLint: 8.14.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'mocha' declared in 'package.json » @studio/eslint-config': Package subpath './src/find' is not defined by "exports" in {...}/node_modules/ramda/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require ({...}/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> ({...}/node_modules/eslint-plugin-mocha/lib/rules/handle-done-callback.js:3:14)
```

I guess the deprecation warning described in #323 turned into a hard failure with the new major version.

**Comment by lo1tuma** [comment]
Looks like a duplicate of #322.

**Comment by mantoni** [comment]
You're right! Closing as duplicate. Thanks 👍
